name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "3.1.300"
      - run: pwsh ./test.ps1
